name: Node.js Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine git.heroku.com login $HEROKU_API_KEY password" > ~/.netrc
          git remote add heroku https://git.heroku.com/nodejs-deployment.git
          git push heroku main --force
